// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const CopyWebpackPlugin = require( 'copy-webpack-plugin' );

// Utilities.
const path = require( 'path' );
const imagesPath = path.resolve( __dirname, './build/images' );

const modulesDir = process.cwd() + '/modules/';

const entryPoints = {
	// Forms module
	'css/Cool_FormKit-forms': path.resolve( modulesDir, 'forms/assets/scss/widgets', 'cool-formkit-forms.scss' ),
	'css/Cool_FormKit-editor': path.resolve( modulesDir, 'forms/assets/scss/', 'editor.scss' ),
	'js/Cool_FormKit-forms-editor': path.resolve( modulesDir, 'forms/assets/js', 'editor.js' ),
	'js/Cool_FormKit-forms-fe': path.resolve( modulesDir, 'forms/assets/js/frontend', 'frontend.js' ),
};

module.exports = {
	...defaultConfig,
	...{
		entry: entryPoints,
		output: {
			...defaultConfig.output,
			path: path.resolve( __dirname, './build' ),
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			new CopyWebpackPlugin( {
				patterns: [
					{
						from: path.resolve( modulesDir, 'forms/assets/images' ),
						to: imagesPath,
					}	
				],
			} ),

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
			} ),
		],
	},
};
